---
- name: Install Apache on Ubuntu
  hosts: ubuntu
  become: yes  # Run tasks with sudo privileges
  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Install Apache2 package
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is started and enabled on boot
      service:
        name: apache2
        state: started
        enabled: yes
